Add dummy exit 1 (failure) and see if the rest will still run (test & sendpr).

diff --git a/.docksal/commands/drupal-coreupdate b/.docksal/commands/drupal-coreupdate
--- a/.docksal/commands/drupal-coreupdate
+++ b/.docksal/commands/drupal-coreupdate
@@ -12,6 +12,7 @@ coreupdate_try() {
      fin drush updb -y                                   && \
      fin drush cr -y                                     && \
      fin drush st
+     exit 1   ## DEBUG: intentional failure added.
   else
      echo "No drupal core update detected."
   fi
